In [4]:
'''3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]] '''

import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr.shape)
print(arr.ndim)
print(arr.size)


(3, 4)
2
12


In [10]:
'''4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[0])


[1 2 3 4]


In [12]:
'''5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[2][3])

12


In [13]:
'''6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr[arr%2 ==1]

array([ 1,  3,  5,  7,  9, 11])

In [15]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
x = np.random.random((3, 3))
print(x)

[[0.08452421 0.07526424 0.72889013]
 [0.96411751 0.14925855 0.57740366]
 [0.99928114 0.79599375 0.64645213]]


In [23]:
'''9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''


arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.shape
print(np.reshape(arr,(6, 2)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [8]:
A2 =np.matrix([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
B2 =np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [9]:
np.multiply(A2,B2)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

In [14]:
A2 =np.matrix([[1, 2, 3] ,[5, 6, 7],[9, 10, 11]])
B2 =np.matrix([[1, 2, 3], [5, 6, 7],[9, 10, 11]])
np.dot(A2,B2)

matrix([[ 38,  44,  50],
        [ 98, 116, 134],
        [158, 188, 218]])

In [11]:
A2+B2

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [12]:
A2-B2

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [13]:
np.divide(A2,B2)

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])